version: '3.8'
services:
  redis-env:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  java-env:
    container_name: java-server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - redis-env